export const AI_MODEL_COST = [
  {
    name: 'Anthropic: Claude 3 Haiku (self-moderated)',
    id: 'anthropic/claude-3-haiku:beta',
    shortName: 'claude-3-haiku',
    inputPrice: 0.35,
    outputPrice: 1.75,
  },
  {
    name: 'Anthropic: Claude 3 Opus (self-moderated)',
    id: 'anthropic/claude-3-opus:beta',
    shortName: 'claude-3-opus',
    inputPrice: 21.0,
    outputPrice: 105.0,
  },
  {
    name: 'Anthropic: Claude 3.7 Sonnet',
    id: 'anthropic/claude-3.7-sonnet',
    shortName: 'claude-3.7-sonnet',
    inputPrice: 4.2,
    outputPrice: 21.0,
  },
  {
    name: 'claude-3-5-haiku-20241022:beta',
    id: 'claude-3-5-haiku-20241022:beta',
    shortName: 'claude-3-5-haiku-20241022',
    inputPrice: 1.4,
    outputPrice: 7.0,
  },
  {
    name: 'Anthropic: Claude 3.5 Sonnet',
    id: 'claude-3.5-sonnet',
    shortName: 'claude-3.5-sonnet',
    inputPrice: 4.2,
    outputPrice: 21.0,
  },
  {
    name: 'Anthropic: Claude Opus 4',
    id: 'claude-opus-4',
    shortName: 'claude-opus-4',
    inputPrice: 21.0,
    outputPrice: 105.0,
  },
  {
    name: 'Anthropic: Claude Opus 4.1',
    id: 'claude-opus-4-1',
    shortName: 'claude-opus-4-1',
    inputPrice: 21.0,
    outputPrice: 105.0,
  },
  {
    name: 'Anthropic: Claude Sonnet 4',
    id: 'claude-sonnet-4',
    shortName: 'claude-sonnet-4',
    inputPrice: 4.2,
    outputPrice: 21.0,
  },
  {
    name: 'Mistral: Codestral 2501',
    id: 'codestral-2501',
    shortName: 'codestral-2501',
    inputPrice: 0.42,
    outputPrice: 1.26,
  },
  {
    name: 'DeepSeek: DeepSeek V3',
    id: 'deepseek-chat',
    shortName: 'deepseek-chat',
    inputPrice: 0.2,
    outputPrice: 0.39,
  },
  {
    name: 'DeepSeek: DeepSeek V3 0324',
    id: 'deepseek-chat-v3-0324',
    shortName: 'deepseek-chat-v3-0324',
    inputPrice: 0.38,
    outputPrice: 1.54,
  },
  {
    name: 'DeepSeek: R1',
    id: 'deepseek/deepseek-r1',
    shortName: 'deepseek-r1',
    inputPrice: 1.12,
    outputPrice: 3.36,
  },
  {
    name: 'DeepSeek: R1 0528',
    id: 'deepseek/deepseek-r1-0528',
    shortName: 'deepseek-r1-0528',
    inputPrice: 0.7,
    outputPrice: 3.05,
  },
  {
    name: 'dolphin-llama-3-70b',
    id: 'dolphin-llama-3-70b',
    shortName: 'dolphin-llama-3-70b',
    inputPrice: 1.8,
    outputPrice: 1.8,
  },
  {
    name: 'Venice: Uncensored',
    id: 'dolphin-mistral-24b-venice-edition',
    shortName: 'dolphin-mistral-24b-venice-edition',
    inputPrice: 0.42,
    outputPrice: 1.4,
  },
  {
    name: 'Dolphin 2.9.2 Mixtral 8x22B',
    id: 'dolphin-mixtral-8x22b',
    shortName: 'dolphin-mixtral-8x22b',
    inputPrice: 1.8,
    outputPrice: 1.8,
  },
  {
    name: 'Google: Gemini 2.0 Flash',
    id: 'gemini-2.0-flash-001',
    shortName: 'gemini-2.0-flash-001',
    inputPrice: 0.2,
    outputPrice: 0.8,
  },
  {
    name: 'gemini-2.0-flash-exp',
    id: 'gemini-2.0-flash-exp',
    shortName: 'gemini-2.0-flash-exp',
    inputPrice: 0.5,
    outputPrice: 1.5,
  },
  {
    name: 'gemini-2.0-flash-thinking-exp',
    id: 'gemini-2.0-flash-thinking-exp',
    shortName: 'gemini-2.0-flash-thinking-exp',
    inputPrice: 0.5,
    outputPrice: 1.5,
  },
  {
    name: 'gemini-2.0-pro-exp-02-05',
    id: 'gemini-2.0-pro-exp-02-05',
    shortName: 'gemini-2.0-pro-exp-02-05',
    inputPrice: 0.5,
    outputPrice: 1.5,
  },
  {
    name: 'Google: Gemini 2.5 Flash',
    id: 'gemini-2.5-flash',
    shortName: 'gemini-2.5-flash',
    inputPrice: 0.42,
    outputPrice: 3.5,
  },
  {
    name: 'Google: Gemini 2.5 Pro',
    id: 'gemini-2.5-pro',
    shortName: 'gemini-2.5-pro',
    inputPrice: 2.5,
    outputPrice: 20.0,
  },
  {
    name: 'gemini-2.5-pro-preview-03-25',
    id: 'gemini-2.5-pro-preview-03-25',
    shortName: 'gemini-2.5-pro-preview-03-25',
    inputPrice: 3.0,
    outputPrice: 20.0,
  },
  {
    name: 'gemini-exp-1114',
    id: 'gemini-exp-1114',
    shortName: 'gemini-exp-1114',
    inputPrice: 0.0,
    outputPrice: 0.0,
  },
  {
    name: 'Google: Gemini 1.5 Flash',
    id: 'google/gemini-flash-1.5',
    shortName: 'gemini-flash-1.5',
    inputPrice: 0.35,
    outputPrice: 1.05,
  },
  {
    name: 'OpenAI: GPT-3.5 Turbo',
    id: 'gpt-3.5-turbo',
    shortName: 'gpt-3.5-turbo',
    inputPrice: 0.7,
    outputPrice: 2.1,
  },
  {
    name: 'OpenAI: GPT-4',
    id: 'gpt-4',
    shortName: 'gpt-4',
    inputPrice: 42.0,
    outputPrice: 84.0,
  },
  {
    name: 'OpenAI: GPT-4 Turbo',
    id: 'gpt-4-turbo',
    shortName: 'gpt-4-turbo',
    inputPrice: 14.0,
    outputPrice: 42.0,
  },
  {
    name: 'OpenAI: GPT-4.1',
    id: 'gpt-4.1',
    shortName: 'gpt-4.1',
    inputPrice: 2.8,
    outputPrice: 0.7,
  },
  {
    name: 'OpenAI: GPT-4.1 Mini',
    id: 'gpt-4.1-mini',
    shortName: 'gpt-4.1-mini',
    inputPrice: 0.56,
    outputPrice: 0.14,
  },
  {
    name: 'OpenAI: GPT-4.1 Nano',
    id: 'gpt-4.1-nano',
    shortName: 'gpt-4.1-nano',
    inputPrice: 0.14,
    outputPrice: 0.04,
  },
  {
    name: 'OpenAI: GPT-4o',
    id: 'gpt-4o',
    shortName: 'gpt-4o',
    inputPrice: 7.0,
    outputPrice: 21.0,
  },
  {
    name: 'OpenAI: GPT-4o-mini',
    id: 'gpt-4o-mini',
    shortName: 'gpt-4o-mini',
    inputPrice: 0.3,
    outputPrice: 1.2,
  },
  {
    name: 'OpenAI: GPT-4o-mini Search Preview',
    id: 'gpt-4o-mini-search-preview',
    shortName: 'gpt-4o-mini-search-preview',
    inputPrice: 0.21,
    outputPrice: 0.84,
  },
  {
    name: 'OpenAI: GPT-4o Search Preview',
    id: 'gpt-4o-search-preview',
    shortName: 'gpt-4o-search-preview',
    inputPrice: 3.5,
    outputPrice: 14.0,
  },
  {
    name: 'OpenAI: GPT-5 (2025-08-07)',
    id: 'gpt-5',
    shortName: 'gpt-5',
    inputPrice: 1.75,
    outputPrice: 14.0,
  },
  {
    name: 'OpenAI: GPT-5',
    id: 'gpt-5-chat',
    shortName: 'gpt-5-chat',
    inputPrice: 1.75,
    outputPrice: 14.0,
  },
  {
    name: 'OpenAI: GPT-5 Mini (2025-08-07)',
    id: 'gpt-5-mini',
    shortName: 'gpt-5-mini',
    inputPrice: 0.35,
    outputPrice: 2.8,
  },
  {
    name: 'OpenAI: GPT-5 Nano (2025-08-07)',
    id: 'gpt-5-nano',
    shortName: 'gpt-5-nano',
    inputPrice: 0.07,
    outputPrice: 0.56,
  },
  {
    name: 'OpenAI: gpt-oss-120b',
    id: 'gpt-oss-120b',
    shortName: 'gpt-oss-120b',
    inputPrice: 0.13,
    outputPrice: 0.06,
  },
  {
    name: 'OpenAI: gpt-oss-20b',
    id: 'gpt-oss-20b',
    shortName: 'gpt-oss-20b',
    inputPrice: 0.06,
    outputPrice: 0.02,
  },
  {
    name: 'grok-2',
    id: 'grok-2',
    shortName: 'grok-2',
    inputPrice: 2.8,
    outputPrice: 14.0,
  },
  {
    name: 'grok-2-beta',
    id: 'grok-2-beta',
    shortName: 'grok-2-beta',
    inputPrice: 7.0,
    outputPrice: 21.0,
  },
  {
    name: 'xAI: Grok 3 Beta',
    id: 'grok-3-beta',
    shortName: 'grok-3-beta',
    inputPrice: 4.2,
    outputPrice: 21.0,
  },
  {
    name: 'xAI: Grok 4',
    id: 'grok-4',
    shortName: 'grok-4',
    inputPrice: 4.2,
    outputPrice: 21.0,
  },
  {
    name: 'MoonshotAI: Kimi K2',
    id: 'kimi-k2',
    shortName: 'kimi-k2',
    inputPrice: 0.2,
    outputPrice: 3.49,
  },
  {
    name: 'NVIDIA: Llama 3.1 Nemotron 70B Instruct',
    id: 'llama-3.1-nemotron-70b-instruct',
    shortName: 'llama-3.1-nemotron-70b-instruct',
    inputPrice: 7.0,
    outputPrice: 2.1,
  },
  {
    name: 'llama-3.1-sonar-huge-128k-online',
    id: 'llama-3.1-sonar-huge-128k-online',
    shortName: 'llama-3.1-sonar-huge-128k-online',
    inputPrice: 2.0,
    outputPrice: 2.0,
  },
  {
    name: 'llama-3.1-sonar-large-128k-online',
    id: 'llama-3.1-sonar-large-128k-online',
    shortName: 'llama-3.1-sonar-large-128k-online',
    inputPrice: 2.0,
    outputPrice: 2.0,
  },
  {
    name: 'Meta: Llama 3.3 70B Instruct',
    id: 'llama-3.3-70b-instruct',
    shortName: 'llama-3.3-70b-instruct',
    inputPrice: 0.21,
    outputPrice: 0.84,
  },
  {
    name: 'Meta: Llama 4 Maverick',
    id: 'llama-4-maverick',
    shortName: 'llama-4-maverick',
    inputPrice: 0.28,
    outputPrice: 0.84,
  },
  {
    name: 'Meta: Llama 4 Scout',
    id: 'llama-4-scout',
    shortName: 'llama-4-scout',
    inputPrice: 0.63,
    outputPrice: 0.7,
  },
  {
    name: 'Meta: Llama 3 70B Instruct',
    id: 'meta-llama/llama-3-70b-instruct',
    shortName: 'llama-3-70b-instruct',
    inputPrice: 1.12,
    outputPrice: 1.12,
  },
  {
    name: 'Meta: Llama 3.1 405B Instruct',
    id: 'meta-llama/llama-3.1-405b-instruct',
    shortName: 'llama-3.1-405b-instruct',
    inputPrice: 4.2,
    outputPrice: 4.2,
  },
  {
    name: 'Mistral: Saba',
    id: 'mistral-saba',
    shortName: 'mistral-saba',
    inputPrice: 0.28,
    outputPrice: 0.84,
  },
  {
    name: 'Mistral Large',
    id: 'mistralai/mistral-large',
    shortName: 'mistral-large',
    inputPrice: 11.2,
    outputPrice: 33.6,
  },
  {
    name: 'mistralai/mistral-medium',
    id: 'mistralai/mistral-medium',
    shortName: 'mistral-medium',
    inputPrice: 3.78,
    outputPrice: 11.34,
  },
  {
    name: 'Mistral Tiny',
    id: 'mistralai/mistral-tiny',
    shortName: 'mistral-tiny',
    inputPrice: 0.35,
    outputPrice: 0.35,
  },
  {
    name: 'Mistral: Mixtral 8x7B Instruct',
    id: 'mistralai/mixtral-8x7b-instruct',
    shortName: 'mixtral-8x7b-instruct',
    inputPrice: 0.76,
    outputPrice: 0.76,
  },
  {
    name: 'Amazon: Nova Pro 1.0',
    id: 'nova-pro-v1',
    shortName: 'nova-pro-v1',
    inputPrice: 1.12,
    outputPrice: 4.48,
  },
  {
    name: 'OpenAI: o1',
    id: 'o1',
    shortName: 'o1',
    inputPrice: 18.0,
    outputPrice: 72.0,
  },
  {
    name: 'OpenAI: o1-mini',
    id: 'o1-mini',
    shortName: 'o1-mini',
    inputPrice: 6.0,
    outputPrice: 24.0,
  },
  {
    name: 'OpenAI: o1-preview',
    id: 'o1-preview',
    shortName: 'o1-preview',
    inputPrice: 18.0,
    outputPrice: 72.0,
  },
  {
    name: 'OpenAI: o1-pro',
    id: 'o1-pro',
    shortName: 'o1-pro',
    inputPrice: 180.0,
    outputPrice: 720.0,
  },
  {
    name: 'OpenAI: o3',
    id: 'o3',
    shortName: 'o3',
    inputPrice: 2.8,
    outputPrice: 11.2,
  },
  {
    name: 'OpenAI: o3 Mini',
    id: 'o3-mini',
    shortName: 'o3-mini',
    inputPrice: 1.54,
    outputPrice: 0.77,
  },
  {
    name: 'OpenAI: o3 Pro',
    id: 'o3-pro',
    shortName: 'o3-pro',
    inputPrice: 28.0,
    outputPrice: 112.0,
  },
  {
    name: 'OpenAI: o4 Mini',
    id: 'o4-mini',
    shortName: 'o4-mini',
    inputPrice: 1.54,
    outputPrice: 6.16,
  },
  {
    name: 'OpenAI: o4 Mini High',
    id: 'o4-mini-high',
    shortName: 'o4-mini-high',
    inputPrice: 1.54,
    outputPrice: 6.16,
  },
  {
    name: 'openrouter-claude-3.5-sonnet',
    id: 'openrouter-claude-3.5-sonnet',
    shortName: 'openrouter-claude-3.5-sonnet',
    inputPrice: 4.2,
    outputPrice: 21.0,
  },
  {
    name: 'qwen3-235b-a22b-07-25',
    id: 'qwen3-235b-a22b-07-25',
    shortName: 'qwen3-235b-a22b-07-25',
    inputPrice: 0.17,
    outputPrice: 0.83,
  },
  {
    name: 'Qwen: Qwen3 Coder',
    id: 'qwen3-coder',
    shortName: 'qwen3-coder',
    inputPrice: 0.42,
    outputPrice: 0.42,
  },
  {
    name: 'Qwen: QwQ 32B Preview',
    id: 'qwq-32b-preview',
    shortName: 'qwq-32b-preview',
    inputPrice: 0.18,
    outputPrice: 0.56,
  },
  {
    name: 'Perplexity: Sonar',
    id: 'sonar',
    shortName: 'sonar',
    inputPrice: 1.4,
    outputPrice: 1.4,
  },
  {
    name: 'Perplexity: Sonar Reasoning',
    id: 'sonar-reasoning',
    shortName: 'sonar-reasoning',
    inputPrice: 1.4,
    outputPrice: 7.0,
  },
];
