import { SATSPERBITCOIN } from "./math";
import { HIDDEN_OPACITY, INSET_WINDOW_WIDTH, WINDOWWIDTH } from "./theme";

const WEBSITE_REGEX =
  /^(https?:\/\/|www\.)[a-z\d]([a-z\d-]*[a-z\d])*(\.[a-z]{2,})+/i;
const hasSpace = /\s/;

const VALID_URL_REGEX =
  /^(https?:\/\/)?([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}(\/[^\s]*)?$/;

const IS_BLITZ_URL_REGEX =
  /^(https?:\/\/)?(www\.)?(blitz-wallet\.com|blitzwalletapp\.com|blitzwallet\.app)(\/[^\s]*)?$/;

const EMAIL_REGEX = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;

const VALID_USERNAME_REGEX = /^(?=.*\p{L})[\p{L}\p{N}_]+$/u;

const IS_SPARK_ID =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const IS_SPARK_REQUEST_ID =
  /^SparkLightning(?:Receive|Send)Request:[0-9a-fA-F\-]+$/;
const IS_BITCOIN_REQUEST_ID = /^SparkCoopExitRequest:[0-9a-fA-F\-]+$/;

const GIFT_DEEPLINK_REGEX =
  /^(?:blitz-wallet:\/\/gift\/|https:\/\/(?:blitz-wallet\.com|blitzwalletapp\.com|blitzwallet\.app)\/gift\/)[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}(#[A-Za-z0-9_-]+)?$/;

const CONTACT_UNIVERSAL_LINK_REGEX =
  /^https?:\/\/(blitzwalletapp\.com|blitzwallet\.app|blitz-wallet\.com)\/u\/[A-Za-z0-9_-]+\/?$/;

const NOSTR_NAME_REGEX = /^[a-zA-Z0-9]+$/;
const NOSTR_RELAY_URL = "wss://relay.getalbypro.com/blitz";

const WHITE_FILTER =
  "brightness(0) saturate(100%) invert(100%) sepia(3%) saturate(7500%) hue-rotate(137deg) brightness(113%) contrast(101%)";

const IS_LETTER_REGEX = /^[A-Za-z]$/;
const BITCOIN_SATS_ICON = "\u20BF";
const HIDDEN_BALANCE_TEXT = `E`;
const BITCOIN_SAT_TEXT = "SAT";
const INFINITY_SYMBOL = "\u221E";

const ECASH_TX_STORAGE_KEY = "CASHU_TRANSACTIONS";
const AUTO_CHANNEL_REBALANCE_STORAGE_KEY = "ACR_STORAGE_KEY";
const ECASH_KEYSET_STORAGE = "ECASH_KEYSET_STORAGE";
const BREEZ_WORKING_DIR_KEY = "BREEZ_WORKING_DIR";
const QUICK_PAY_STORAGE_KEY = "FAST_PAY_SETTINGS";
const LOGIN_SECUITY_MODE_KEY = "LOGIN_SECURITY_MODE";
const MIGRATE_ECASH_STORAGE_KEY = "MIGRATE_ECASH";
const THEME_LOCAL_STORAGE_KEY = "THEME_SETTINGS";
const THEME_DARK_MODE_KEY = "DARK_MODE_THEME";
const POINT_OF_SALE_PAYOUT_DESCRIPTION = "Blitz Tips Payout";
const NWC_SECURE_STORE_KEY = "NWC_SECURE_STORE_KEY";
const NWC_SECURE_STORE_MNEMOINC = "NWC_SECURE_STORE_MNEMOINC";
const NWC_LOACAL_STORE_KEY = "NWC_LOACAL_STORE_KEY";
const LAST_LOADED_BLITZ_LOCAL_STOREAGE_KEY = "LAST_LOADED_BLTIZ";
const BLITZ_PROFILE_IMG_STORAGE_REF = "profile_pictures";
const BLITZ_DEFAULT_PAYMENT_DESCRIPTION = "";
const BIOMETRIC_KEY = "biometricEncryptionKey";
const LOGIN_SECURITY_MODE_TYPE_KEY = "LOGIN_SECURITY_MODE_TYPE";
const SPARK_CACHED_BALANCE_KEY = "CACHED_SPARK_BALANCE";
const NWC_IDENTITY_PUB_KEY = "NWC_WALLET_PUB_KEY";
const GENERATED_BITCOIN_ADDRESSES = "GENERATED_BITCOIN_ADDRESSES";
const SHOPS_DIRECTORY_KEY = "SHOPS_CURRENCY_LOCATION";
const RANDOM_LOGIN_KEYBOARD_LAYOUT_KEY = "RANDOM_KEYBOARD_LAYOUT_KEY";
const PERSISTED_LOGIN_COUNT_KEY = "PERSISTED_LOGIN_COUNT_KEY";
const GIFT_DERIVE_PATH_CUTOFF = 1763650239108;

const BLITZ_SUPPORT_DEFAULT_PAYMENT_DESCRIPTION = "Blitz support";
const CUSTODY_ACCOUNTS_STORAGE_KEY = "CUSTODY_ACCOUNTS";
const BLITZ_PAYMENT_DEEP_LINK_SCHEMES = [
  "bitcoin",
  "BITCOIN",
  "lightning",
  "LIGHTNING",
  "lnurl",
  "LNURL",
  "lnurlp",
  "LNURLP",
  "lnurlw",
  "LNURLW",
  "keyauth",
];

const CHATGPT_INPUT_COST = 10 / 1000000;
const CHATGPT_OUTPUT_COST = 30 / 1000000;
const STARTING_INDEX_FOR_GIFTS_DERIVE = 1000;

const MIN_CHANNEL_OPEN_FEE = 500_000;
const MAX_CHANNEL_OPEN_FEE = 1_000_000;
const BLITZ_RECEIVE_FEE = 0.0;
const BLITZ_SEND_FEE = 0.0;
const LIQUID_DEFAULT_FEE = 30;
const MAX_ECASH_RECEIVE = 50_000;
const MAX_ECASH_BALANCE = 50_000;
const SMALLEST_ONCHAIN_SPARK_SEND_AMOUNT = 10_000;
const LIQUID_NON_BITCOIN_DRAIN_LIMIT = 10;

const CONTENT_KEYBOARD_OFFSET = 10;

const BLITZ_GOAL_USER_COUNT = 1_000_000;

const IS_DONTATION_PAYMENT_BUFFER = 10_000;
const SKELETON_ANIMATION_SPEED = 1200;
const TOKEN_TICKER_MAX_LENGTH = 10;

const BACKGROUND_THRESHOLD_MS = 2 * 60 * 1000;
const FORCE_RESET_SPAARK_STATE_MS = 6 * 60 * 1000;

const DEFAULT_PAYMENT_EXPIRY_SEC = 60 * 60 * 12;

export {
  //   COLORS,
  //   FONT,
  //   SIZES,
  //   SHADOWS,
  //   ICONS,
  //   CENTER,
  //   BTN,
  //   Background,
  SATSPERBITCOIN,
  // BLOCKED_NAVIGATION_PAYMENT_CODES,
  WEBSITE_REGEX,
  hasSpace,
  ECASH_TX_STORAGE_KEY,
  VALID_URL_REGEX,
  CHATGPT_INPUT_COST,
  CHATGPT_OUTPUT_COST,
  MIN_CHANNEL_OPEN_FEE,
  MAX_CHANNEL_OPEN_FEE,
  EMAIL_REGEX,
  VALID_USERNAME_REGEX,
  BLITZ_RECEIVE_FEE,
  BLITZ_SEND_FEE,
  AUTO_CHANNEL_REBALANCE_STORAGE_KEY,
  ECASH_KEYSET_STORAGE,
  BREEZ_WORKING_DIR_KEY,
  QUICK_PAY_STORAGE_KEY,
  BLITZ_DEFAULT_PAYMENT_DESCRIPTION,
  LOGIN_SECUITY_MODE_KEY,
  LIQUID_DEFAULT_FEE,
  BITCOIN_SATS_ICON,
  MIGRATE_ECASH_STORAGE_KEY,
  CONTENT_KEYBOARD_OFFSET,
  HIDDEN_BALANCE_TEXT,
  MAX_ECASH_RECEIVE,
  MAX_ECASH_BALANCE,
  LIQUID_NON_BITCOIN_DRAIN_LIMIT,
  POINT_OF_SALE_PAYOUT_DESCRIPTION,
  BLITZ_GOAL_USER_COUNT,
  CUSTODY_ACCOUNTS_STORAGE_KEY,
  BLITZ_SUPPORT_DEFAULT_PAYMENT_DESCRIPTION,
  IS_DONTATION_PAYMENT_BUFFER,
  LAST_LOADED_BLITZ_LOCAL_STOREAGE_KEY,
  BLITZ_PROFILE_IMG_STORAGE_REF,
  SKELETON_ANIMATION_SPEED,
  BIOMETRIC_KEY,
  IS_LETTER_REGEX,
  BITCOIN_SAT_TEXT,
  LOGIN_SECURITY_MODE_TYPE_KEY,
  IS_SPARK_REQUEST_ID,
  NOSTR_NAME_REGEX,
  SPARK_CACHED_BALANCE_KEY,
  TOKEN_TICKER_MAX_LENGTH,
  SMALLEST_ONCHAIN_SPARK_SEND_AMOUNT,
  IS_BITCOIN_REQUEST_ID,
  NWC_SECURE_STORE_KEY,
  NWC_SECURE_STORE_MNEMOINC,
  NWC_LOACAL_STORE_KEY,
  IS_SPARK_ID,
  NOSTR_RELAY_URL,
  NWC_IDENTITY_PUB_KEY,
  SHOPS_DIRECTORY_KEY,
  INFINITY_SYMBOL,
  GENERATED_BITCOIN_ADDRESSES,
  RANDOM_LOGIN_KEYBOARD_LAYOUT_KEY,
  PERSISTED_LOGIN_COUNT_KEY,
  BLITZ_PAYMENT_DEEP_LINK_SCHEMES,
  IS_BLITZ_URL_REGEX,
  STARTING_INDEX_FOR_GIFTS_DERIVE,
  GIFT_DEEPLINK_REGEX,
  GIFT_DERIVE_PATH_CUTOFF,
  CONTACT_UNIVERSAL_LINK_REGEX,
  BACKGROUND_THRESHOLD_MS,
  FORCE_RESET_SPAARK_STATE_MS,
  DEFAULT_PAYMENT_EXPIRY_SEC,
  WHITE_FILTER,
  THEME_LOCAL_STORAGE_KEY,
  THEME_DARK_MODE_KEY,
  WINDOWWIDTH,
  HIDDEN_OPACITY,
  INSET_WINDOW_WIDTH,
};
