export const fiatCurrencies = [
  {info: {spacing: null, name: 'Australian Dollar'}, id: 'AUD'},
  {info: {spacing: null, name: 'Baht'}, id: 'THB'},
  {info: {spacing: null, name: 'Balboa'}, id: 'PAB'},
  {info: {spacing: null, name: 'Bolivar Soberano'}, id: 'VES'},
  {info: {spacing: null, name: 'Boliviano'}, id: 'BOB'},
  {info: {spacing: null, name: 'Bulgarian Lev'}, id: 'BGN'},
  {info: {spacing: null, name: 'CFA Franc BCEAO'}, id: 'XOF'},
  {info: {spacing: null, name: 'Canadian Dollar'}, id: 'CAD'},
  {info: {spacing: null, name: 'Cost Rican Colon'}, id: 'CRC'},
  {info: {spacing: null, name: 'Czech Koruna'}, id: 'CZK'},
  {info: {spacing: null, name: 'Danish Krone'}, id: 'DKK'},
  {info: {spacing: null, name: 'Dong'}, id: 'VND'},
  {info: {spacing: null, name: 'Euro'}, id: 'EUR'},
  {info: {spacing: null, name: 'Forint'}, id: 'HUF'},
  {info: {spacing: null, name: 'Guaraní'}, id: 'PYG'},
  {info: {spacing: null, name: 'Hong Kong Dollar'}, id: 'HKD'},
  {info: {spacing: null, name: 'Indian Rupee'}, id: 'INR'},
  {info: {spacing: null, name: 'Jamaican Dollar'}, id: 'JMD'},
  {info: {spacing: null, name: 'Kenyan Shilling'}, id: 'KES'},
  {info: {spacing: null, name: 'Lebanese Pound'}, id: 'LBP'},
  {info: {spacing: null, name: 'Lempira'}, id: 'HNL'},
  {info: {spacing: null, name: 'Malaysian Ringgit'}, id: 'MYR'},
  {info: {spacing: null, name: 'Naira'}, id: 'NGN'},
  {info: {spacing: null, name: 'Namibia Dollar'}, id: 'NAD'},
  {info: {spacing: null, name: 'Netherlands Antillean Guilder'}, id: 'ANG'},
  {info: {spacing: null, name: 'New Israeli Shekel'}, id: 'ILS'},
  {info: {spacing: null, name: 'New Taiwan Dollar'}, id: 'TWD'},
  {info: {spacing: null, name: 'New Zealand Dollar'}, id: 'NZD'},
  {info: {spacing: null, name: 'Norwegian Krone'}, id: 'NOK'},
  {info: {spacing: null, name: 'Pakistan Rupee'}, id: 'PKR'},
  {info: {spacing: null, name: 'Peso Argentino'}, id: 'ARS'},
  {info: {spacing: null, name: 'Peso Chileno'}, id: 'CLP'},
  {info: {spacing: null, name: 'Peso Colombiano'}, id: 'COP'},
  {info: {spacing: null, name: 'Peso Dominicano'}, id: 'DOP'},
  {info: {spacing: null, name: 'Peso Mexicano'}, id: 'MXN'},
  {info: {spacing: null, name: 'Peso Uruguayo'}, id: 'UYU'},
  {info: {spacing: null, name: 'Piso'}, id: 'PHP'},
  {info: {spacing: null, name: 'Pound Sterling'}, id: 'GBP'},
  {info: {spacing: null, name: 'Quetzal'}, id: 'GTQ'},
  {info: {spacing: null, name: 'Rand'}, id: 'ZAR'},
  {info: {spacing: null, name: 'Real'}, id: 'BRL'},
  {info: {spacing: null, name: 'Romanian Leu'}, id: 'RON'},
  {info: {spacing: null, name: 'Rupiah'}, id: 'IDR'},
  {info: {spacing: null, name: 'Russian Ruble'}, id: 'RUB'},
  {info: {spacing: null, name: 'Singapore Dollar'}, id: 'SGD'},
  {info: {spacing: null, name: 'Sol'}, id: 'PEN'},
  {info: {spacing: null, name: 'Swedish Krona'}, id: 'SEK'},
  {info: {spacing: null, name: 'Swiss Franc'}, id: 'CHF'},
  {info: {spacing: null, name: 'Trinidad and Tobago Dollar'}, id: 'TTD'},
  {info: {spacing: null, name: 'Turkish Lira'}, id: 'TRY'},
  {info: {spacing: null, name: 'UAE Dirham'}, id: 'AED'},
  {info: {spacing: null, name: 'US Dollar'}, id: 'USD'},
  {info: {spacing: null, name: 'Yuan Renminbi'}, id: 'CNY'},
  {info: {spacing: null, name: 'Zambian Kwacha'}, id: 'ZMW'},
  {info: {spacing: null, name: 'Zloty'}, id: 'PLN'},
  {info: {spacing: null, name: '円'}, id: 'JPY'},
  {info: {spacing: null, name: '원'}, id: 'KRW'},
];
