name: "[CI] ESLint Check"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  eslint:
    name: Run ESLint
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: Clean npm cache
        run: |
          npm cache clean --force

      - name: Install dependencies
        run: |
          set -euxo pipefail
          rm -rf node_modules package-lock.json
          npm install --prefer-online

      - name: Run ESLint
        run: |
          set -euxo pipefail
          npm run lint
